version: '3.3'

services:
    phcsim-webapi:
        image: phcsim-webapi
        container_name: phcsim-webapi 
        build:
            context: ./PHCSim.Backend
            dockerfile: Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./PHCSim.Backend:/app
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on: 
            - reverse-proxy
            - mongodb

    frontend:
        image: frontend
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true

    reverse-proxy:
        image: reverse-proxy
        container_name: reverse-proxy
        build:
            context: ./PHCSim.Backend/PHCSim.WebApi/Nginx
            dockerfile: Dockerfile
        ports:
            - '80:80'

    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: phcsim123
            MONGO_INITDB_DATABASE: phcsim
            MONGO_DATA_DIR: /data/db
            MONGO_LOG_DIR: /dev/null
        ports:
            - "27017:27017"
        volumes:
            - mongodbdata:/data/db

volumes:
    frontend:
        driver: local
    phcsim-webapi:
        driver: local
    mongodbdata:
        driver: local