version: '3.3'

services:
    phcsim-webapi:
        image: phcsim-webapi
        container_name: phcsim-webapi 
        build:
            context: ./PHCSim.Backend
            dockerfile: Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./PHCSim.Backend:/app
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on: 
            - reverse-proxy

    frontend:
        image: frontend
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true

    reverse-proxy:
        image: reverse-proxy
        container_name: reverse-proxy
        build:
            context: ./PHCSim.Backend/PHCSim.WebApi/Nginx
            dockerfile: Dockerfile
        ports:
            - '80:80'

volumes:
    frontend:
        driver: local
    phcsim-webapi:
        driver: local